#python3 DAG.py ../data/interactome-weights.txt ../data/prepare-G0/ground_truth/IL1-G0.txt ../NetPath/IL1-nodes.txt -k 25 -c 1 -o ../output/ground_truth-G0/IL1_c1_k25.txt > ../output/ground_truth-G0/IL1_c1_k25.log
python3 DAG.py ../data/interactome-weights.txt ../data/prepare-G0/ground_truth/BCR-G0.txt ../NetPath/BCR-nodes.txt -k 25 -c 1 -o ../output/ground_truth-G0/BCR_c1_k25.txt > ../output/ground_truth-G0/BCR_c1_k25.log
python3 DAG.py ../data/interactome-weights.txt ../data/prepare-G0/ground_truth/TGFbetaReceptor-G0.txt ../NetPath/TGF_beta_Receptor-nodes.txt -k 25 -c 1 -o ../output/ground_truth-G0/TGFbetaReceptor_c1_k25.txt > ../output/ground_truth-G0/TGFbetaReceptor_c1_k25.log
python3 DAG.py ../data/interactome-weights.txt ../data/prepare-G0/ground_truth/TCR-G0.txt ../NetPath/TCR-nodes.txt -k 25 -c 1 -o ../output/ground_truth-G0/TCR_c1_k25.txt > ../output/ground_truth-G0/TCR_c1_k25.log
python3 DAG.py ../data/interactome-weights.txt ../data/prepare-G0/ground_truth/EGFR1-G0.txt ../NetPath/EGFR1-nodes.txt -k 25 -c 1 -o ../output/ground_truth-G0/EGFR1_c1_k25.txt > ../output/ground_truth-G0/EGFR1_c1_k25.log
python3 DAG.py ../data/interactome-weights.txt ../data/prepare-G0/ground_truth/Wnt-G0.txt ../NetPath/Wnt-nodes.txt -k 25 -c 1 -o ../output/ground_truth-G0/Wnt_c1_k25.txt > ../output/ground_truth-G0/Wnt_c1_k25.log

python3 DAG.py ../data/interactome-weights.txt ../data/prepare-G0/ground_truth/IL1-G0.txt ../NetPath/IL1-nodes.txt -k 25 -c 2 -o ../output/ground_truth-G0/IL1_c2_k25.txt > ../output/ground_truth-G0/IL1_c2_k25.log
python3 DAG.py ../data/interactome-weights.txt ../data/prepare-G0/ground_truth/BCR-G0.txt ../NetPath/BCR-nodes.txt -k 25 -c 2 -o ../output/ground_truth-G0/BCR_c2_k25.txt > ../output/ground_truth-G0/BCR_c2_k25.log
python3 DAG.py ../data/interactome-weights.txt ../data/prepare-G0/ground_truth/TGFbetaReceptor-G0.txt ../NetPath/TGF_beta_Receptor-nodes.txt -k 25 -c 2 -o ../output/ground_truth-G0/TGFbetaReceptor_c2_k25.txt > ../output/ground_truth-G0/TGFbetaReceptor_c2_k25.log
python3 DAG.py ../data/interactome-weights.txt ../data/prepare-G0/ground_truth/TCR-G0.txt ../NetPath/TCR-nodes.txt -k 25 -c 2 -o ../output/ground_truth-G0/TCR_c2_k25.txt > ../output/ground_truth-G0/TCR_c2_k25.log
python3 DAG.py ../data/interactome-weights.txt ../data/prepare-G0/ground_truth/EGFR1-G0.txt ../NetPath/EGFR1-nodes.txt -k 25 -c 2 -o ../output/ground_truth-G0/EGFR1_c2_k25.txt > ../output/ground_truth-G0/EGFR1_c2_k25.log
python3 DAG.py ../data/interactome-weights.txt ../data/prepare-G0/ground_truth/Wnt-G0.txt ../NetPath/Wnt-nodes.txt -k 25 -c 2 -o ../output/ground_truth-G0/Wnt_c2_k25.txt > ../output/ground_truth-G0/Wnt_c2_k25.log
