#python3 ../alg/DAG.py ../../data/interactome-weights.txt ../../data/prepare-G0/pathlinker/IL1-G0.txt ../../data/netpath//IL1-nodes.txt -k 100 -c 1 -o ../../output/pathlinker-G0/IL1_c1_k100.txt > ../../output/pathlinker-G0/IL1_c1_k100.log
python3 ../alg/DAG.py ../../data/interactome-weights.txt ../../data/prepare-G0/pathlinker/BCR-G0.txt ../../data/netpath//BCR-nodes.txt -k 100 -c 1 -o ../../output/pathlinker-G0/BCR_c1_k100.txt > ../../output/pathlinker-G0/BCR_c1_k100.log
python3 ../alg/DAG.py ../../data/interactome-weights.txt ../../data/prepare-G0/pathlinker/TGFbetaReceptor-G0.txt ../../data/netpath//TGF_beta_Receptor-nodes.txt -k 100 -c 1 -o ../../output/pathlinker-G0/TGFbetaReceptor_c1_k100.txt > ../../output/pathlinker-G0/TGFbetaReceptor_c1_k100.log
#python3 ../alg/DAG.py ../../data/interactome-weights.txt ../../data/prepare-G0/pathlinker/TCR-G0.txt ../../data/netpath//TCR-nodes.txt -k 100 -c 1 -o ../../output/pathlinker-G0/TCR_c1_k100.txt > ../../output/pathlinker-G0/TCR_c1_k100.log
#python3 ../alg/DAG.py ../../data/interactome-weights.txt ../../data/prepare-G0/pathlinker/EGFR1-G0.txt ../../data/netpath//EGFR1-nodes.txt -k 100 -c 1 -o ../../output/pathlinker-G0/EGFR1_c1_k100.txt > ../../output/pathlinker-G0/EGFR1_c1_k100.log
python3 ../alg/DAG.py ../../data/interactome-weights.txt ../../data/prepare-G0/pathlinker/Wnt-G0.txt ../../data/netpath//Wnt-nodes.txt -k 100 -c 1 -o ../../output/pathlinker-G0/Wnt_c1_k100.txt > ../../output/pathlinker-G0/Wnt_c1_k100.log

python3 ../alg/DAG.py ../../data/interactome-weights.txt ../../data/prepare-G0/pathlinker/IL1-G0.txt ../../data/netpath//IL1-nodes.txt -k 100 -c 2 -o ../../output/pathlinker-G0/IL1_c2_k100.txt > ../../output/pathlinker-G0/IL1_c2_k100.log
python3 ../alg/DAG.py ../../data/interactome-weights.txt ../../data/prepare-G0/pathlinker/BCR-G0.txt ../../data/netpath//BCR-nodes.txt -k 100 -c 2 -o ../../output/pathlinker-G0/BCR_c2_k100.txt > ../../output/pathlinker-G0/BCR_c2_k100.log
python3 ../alg/DAG.py ../../data/interactome-weights.txt ../../data/prepare-G0/pathlinker/TGFbetaReceptor-G0.txt ../../data/netpath//TGF_beta_Receptor-nodes.txt -k 100 -c 2 -o ../../output/pathlinker-G0/TGFbetaReceptor_c2_k100.txt > ../../output/pathlinker-G0/TGFbetaReceptor_c2_k100.log
python3 ../alg/DAG.py ../../data/interactome-weights.txt ../../data/prepare-G0/pathlinker/TCR-G0.txt ../../data/netpath//TCR-nodes.txt -k 100 -c 2 -o ../../output/pathlinker-G0/TCR_c2_k100.txt > ../../output/pathlinker-G0/TCR_c2_k100.log
#python3 ../alg/DAG.py ../../data/interactome-weights.txt ../../data/prepare-G0/pathlinker/EGFR1-G0.txt ../../data/netpath//EGFR1-nodes.txt -k 100 -c 2 -o ../../output/pathlinker-G0/EGFR1_c2_k100.txt > ../../output/pathlinker-G0/EGFR1_c2_k100.log
python3 ../alg/DAG.py ../../data/interactome-weights.txt ../../data/prepare-G0/pathlinker/Wnt-G0.txt ../../data/netpath//Wnt-nodes.txt -k 100 -c 2 -o ../../output/pathlinker-G0/Wnt_c2_k100.txt > ../../output/pathlinker-G0/Wnt_c2_k100.log
